name: Android CMake Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        components: |
          platform-tools
          build-tools;28.0.3
          platforms;android-28

    - name: Install NDK and CMake
      run: |
        sdkmanager "ndk;21.0.6113669" "cmake;3.10.2.4988404"

    - name: Build for armeabi-v7a
      run: |
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.0.6113669
        mkdir -p build/armeabi-v7a && cd build/armeabi-v7a
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-21 ../..
        cmake --build .
        cd ../..

    - name: Build for arm64-v8a
      run: |
        mkdir -p build/arm64-v8a && cd build/arm64-v8a
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 ../..
        cmake --build .
        cd ../..

    - name: Build for armeabi
      run: |
        mkdir -p build/armeabi && cd build/armeabi
        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-21 ../..
        cmake --build .
